export const LOAD_CATEGORIES_INIT = "LOAD_CATEGORIES_INIT";
export const LOAD_CATEGORIES_SUCCEED = "LOAD_CATEGORIES_SUCCEED";
export const LOAD_CATEGORIES_FAILED = "LOAD_CATEGORIES_FAILED";

export const LOAD_RECIPES_INIT = "LOAD_RECIPES_INIT";
export const LOAD_RECIPES_SUCCEED = "LOAD_RECIPES_SUCCEED";
export const LOAD_RECIPES_FAILED = "LOAD_RECIPES_FAILED";

export const LOAD_RECIPE_INIT = "LOAD_RECIPE_INIT";
export const LOAD_RECIPE_SUCCEED = "LOAD_RECIPE_SUCCEED";
export const LOAD_RECIPE_FAILED = "LOAD_RECIPE_FAILED";
